### ISSUE TITLE
Error: Maven resources not found for Scala version 2.12, but I'm using Scala version 2.13.12

### ISSUE THREAD

**Issue by lulunac27a** [raquo/Laminar#156]
The Maven resources were not found when I run the `sbt` command. The error was generated in plugins.sbt: `addSbtPlugin("org.scala.js" % "sbt-scalajs" % "1.15.0")`, but I use Scala version 2.13.12: `scalaVersion := "2.13.12"
`, not Scala version 2.12:
```
[warn] 	Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes
[warn] 		org.scala.js:sbt-scalajs:1.15.0 (sbtVersion=1.0, scalaVersion=2.12)
[warn] 	Note: Unresolved dependencies path:
[error] sbt.librarymanagement.ResolveException: Error downloading org.scala.js:sbt-scalajs;sbtVersion=1.0;scalaVersion=2.12:1.15.0
[error]   Not found
[error]   not found: https://repo1.maven.org/maven2/org/scala/js/sbt-scalajs_2.12_1.0/1.15.0/sbt-scalajs-1.15.0.pom
[error]   not found: /Users/lulu/.ivy2/localorg.scala.js/sbt-scalajs/scala_2.12/sbt_1.0/1.15.0/ivys/ivy.xml
[error]   not found: https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.scala.js/sbt-scalajs/scala_2.12/sbt_1.0/1.15.0/ivys/ivy.xml
[error]   not found: https://repo.typesafe.com/typesafe/ivy-releases/org.scala.js/sbt-scalajs/scala_2.12/sbt_1.0/1.15.0/ivys/ivy.xml
[error] 	at lmcoursier.CoursierDependencyResolution.unresolvedWarningOrThrow(CoursierDependencyResolution.scala:344)
[error] 	at lmcoursier.CoursierDependencyResolution.$anonfun$update$38(CoursierDependencyResolution.scala:313)
[error] 	at scala.util.Either$LeftProjection.map(Either.scala:573)
[error] 	at lmcoursier.CoursierDependencyResolution.update(CoursierDependencyResolution.scala:313)
[error] 	at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:60)
[error] 	at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:60)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:134)
[error] 	at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:74)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$20(LibraryManagement.scala:147)
[error] 	at scala.util.control.Exception$Catch.apply(Exception.scala:228)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:147)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:128)
[error] 	at sbt.util.Tracked$.$anonfun$inputChangedW$1(Tracked.scala:220)
[error] 	at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:161)
[error] 	at sbt.Classpaths$.$anonfun$updateTask0$1(Defaults.scala:3801)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:63)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:69)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:283)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:24)
[error] 	at sbt.Execute.work(Execute.scala:292)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:283)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:65)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[error] 	at java.base/java.lang.Thread.run(Thread.java:1583)
[error] (update) sbt.librarymanagement.ResolveException: Error downloading org.scala.js:sbt-scalajs;sbtVersion=1.0;scalaVersion=2.12:1.15.0
[error]   Not found
[error]   not found: https://repo1.maven.org/maven2/org/scala/js/sbt-scalajs_2.12_1.0/1.15.0/sbt-scalajs-1.15.0.pom
[error]   not found: /Users/lulu/.ivy2/localorg.scala.js/sbt-scalajs/scala_2.12/sbt_1.0/1.15.0/ivys/ivy.xml
[error]   not found: https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.scala.js/sbt-scalajs/scala_2.12/sbt_1.0/1.15.0/ivys/ivy.xml
[error]   not found: https://repo.typesafe.com/typesafe/ivy-releases/org.scala.js/sbt-scalajs/scala_2.12/sbt_1.0/1.15.0/ivys/ivy.xml
[warn] Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? (default: r)
```

**Comment by raquo** [comment]
Did you by any chance run the `sbt` command in the same directory where you put the `plugins.sbt` file? `plugins.sbt` should be inside `./project` directory, and the `sbt` command should be run from the parent directory (where your `build.sbt` is located). See the build setup and build instructions in https://github.com/raquo/laminar-full-stack-demo/ for reference.

**Comment by lulunac27a** [comment]
Yes it's working when I use the `sbt` command, but how can I compile the files to generate JavaScript files automatically?

**Comment by raquo** [comment]
Not sure I understand what you're asking... Do you want sbt to watch for changes in your scala code, and automatically compile them to JS when a change is detected?

The project I linked has this set up, see its build config, and see instructions [here](https://github.com/raquo/laminar-full-stack-demo/?tab=readme-ov-file#development-setup). `sbt ~fastLinkJS` is the key command, but it also needs Vite bundler configuration (also already done in that project).

**Comment by lulunac27a** [comment]
Yes, by initializing `npm`

**Comment by keynmol** [comment]
@lulunac27a you've made a mistake in the org name for the SBT plugin:

Your code uses `org.scala.js` in `addSbtPlugin("org.scala.js" % "sbt-scalajs" % "1.15.0")`, but it's actually supposed to be `org.scala-js` (`-` vs `.`)

**Comment by lulunac27a** [comment]
I use `libraryDependencies += "org.scala-js" %%% "scalajs-dom" % "2.4.0"`, but still gets errors while running `sbt fastLinkJS` command:
```
[warn] 	Note: Unresolved dependencies path:
[error] Couldn't run bloopGenerate. The issue could be caused by failing to compile the project.
[error] sbt.librarymanagement.ResolveException: Error downloading org.scala.js:sbt-scalajs;sbtVersion=1.0;scalaVersion=2.12:1.15.0
[error]   Not found
[error]   Not found
[error]   not found: https://repo1.maven.org/maven2/org/scala/js/sbt-scalajs_2.12_1.0/1.15.0/sbt-scalajs-1.15.0.pom
[error]   not found: /Users/lulu/.ivy2/localorg.scala.js/sbt-scalajs/scala_2.12/sbt_1.0/1.15.0/ivys/ivy.xml
[error]   not found: https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.scala.js/sbt-scalajs/scala_2.12/sbt_1.0/1.15.0/ivys/ivy.xml
[error]   not found: https://repo.typesafe.com/typesafe/ivy-releases/org.scala.js/sbt-scalajs/scala_2.12/sbt_1.0/1.15.0/ivys/ivy.xml
[error] 	at lmcoursier.CoursierDependencyResolution.unresolvedWarningOrThrow(CoursierDependencyResolution.scala:344)
[error] 	at lmcoursier.CoursierDependencyResolution.$anonfun$update$38(CoursierDependencyResolution.scala:313)
[error] 	at scala.util.Either$LeftProjection.map(Either.scala:573)
[error] 	at lmcoursier.CoursierDependencyResolution.update(CoursierDependencyResolution.scala:313)
[error] 	at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:60)
[error] 	at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:60)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:134)
[error] 	at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:74)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$20(LibraryManagement.scala:147)
[error] 	at scala.util.control.Exception$Catch.apply(Exception.scala:228
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:147)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:128)
[error] 	at sbt.util.Tracked$.$anonfun$inputChangedW$1(Tracked.scala:220
[error] 	at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:161)
[error] 	at sbt.Classpaths$.$anonfun$updateTask0$1(Defaults.scala:3801)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:63)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:69)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:283)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:24)
[error] 	at sbt.Execute.work(Execute.scala:292)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:283)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:65)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[error] 	at java.base/java.lang.Thread.run(Thread.java:1583)
[error] (update) sbt.librarymanagement.ResolveException: Error downloading org.scala.js:sbt-scalajs;sbtVersion=1.0;scalaVersion=2.12:1.15.0
[error]   Not found
[error]   Not found
[error]   not found: https://repo1.maven.org/maven2/org/scala/js/sbt-scalajs_2.12_1.0/1.15.0/sbt-scalajs-1.15.0.pom
[error]   not found: /Users/lulu/.ivy2/localorg.scala.js/sbt-scalajs/scala_2.12/sbt_1.0/1.15.0/ivys/ivy.xml
[error]   not found: https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.scala.js/sbt-scalajs/scala_2.12/sbt_1.0/1.15.0/ivys/ivy.xml
[error]   not found: https://repo.typesafe.com/typesafe/ivy-releases/org.scala.js/sbt-scalajs/scala_2.12/sbt_1.0/1.15.0/ivys/ivy.xml
```

**Comment by keynmol** [comment]
The problem is in the plugins.sbt, not in build.sbt.

**Comment by lulunac27a** [comment]
It works when I change from `org.scala.js` to `org.scala-js` in plugins.sbt.
